# Generated by Django 4.0.5 on 2022-06-01 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 18, 30, 58, 431716, tzinfo=utc), verbose_name='Joined'),
        ),
    ]
